---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/hello_world
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
---
spring:
  config:
    activate:
      on-profile: dynamodb
---
spring:
  profiles:
    active: postgres

server:
  tomcat:
    threads:
      max: 50