---
spring:
  config:
    activate:
      on-profile: postgres
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/hello_world
    username: postgres
    password: postgres
    pool:
      max-size: 10
logging:
  level:
    org.jooq.Constants: OFF
---
spring:
  config:
    activate:
      on-profile: dynamodb
---
spring:
  profiles:
    active: postgres,jooq
  main:
    banner-mode: off

server:
  http2:
    enabled: true
