spring:
  main:
    banner-mode: off
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/hello_world
    username: postgres
    password: postgres
    pool:
      max-size: 10

server:
  http2:
    enabled: true
  netty:
    connection-timeout: 60

logging:
  level:
    io.netty.channel.DefaultChannelPipeline: ERROR
